SELECT C.NM_CONVENIO, COUNT(*) AS QTD FROM USRDBVAH.TB_GUIABI_GUIA G
  LEFT JOIN DBAMV.TB_ATENDIME ATD ON ATD.CD_ATENDIMENTO = G.CD_ATENDIMENTO
  LEFT JOIN DBAMV.CONVENIO C ON C.CD_CONVENIO = ATD.CD_CONVENIO
WHERE DT_RESPOSTA_CONVENIO IS NULL
  AND DT_GUIA > to_date('2016-08-01', 'YYYY-MM-DD')
GROUP BY C.NM_CONVENIO
ORDER BY QTD DESC;

SELECT C.NM_CONVENIO, CAST(AVG(G.DT_RESPOSTA_CONVENIO - G.DT_GUIA) AS INT) AS DIFF FROM USRDBVAH.TB_GUIABI_GUIA G
  LEFT JOIN DBAMV.TB_ATENDIME ATD ON ATD.CD_ATENDIMENTO = G.CD_ATENDIMENTO
  LEFT JOIN DBAMV.CONVENIO C ON C.CD_CONVENIO = ATD.CD_CONVENIO
WHERE DT_RESPOSTA_CONVENIO IS NOT NULL
      AND DT_GUIA > to_date('2016-08-01', 'YYYY-MM-DD')
GROUP BY C.NM_CONVENIO
ORDER BY DIFF DESC;